apiVersion: v1
kind: Service
metadata:
  name: postgres-external
  namespace: modulith
spec:
  ports:
    - port: 5432
  type: ExternalName
  externalName: pg-minikube-postgresql.modulith-argo.svc.cluster.local